main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('plans/', views.plans_index, name='index'), 
    path('plans/<int:plan_id>/', views.plans_detail, name='detail'),
    path('plans/create/', views.PlanCreate.as_view(), name='plans_create'),
    path('plans/<int:pk>/update/', views.PlanUpdate.as_view(), name='plans_update'),
    path('plans/<int:pk>/delete/', views.PlanDelete.as_view(), name='plans_delete'),
    path('plans/<int:plan_id>/add_meal/', views.add_meal, name='add_meal'),
    path('meals/<int:pk>/delete', views.MealDelete.as_view(), name='meal_delete'),
    path('recipes/', views.RecipeList.as_view(), name='recipes_index'),
    path('recipes/<int:recipe_id>/', views.recipes_detail, name='recipes_detail'),
    path('recipes/create/', views.RecipeCreate.as_view(), name='recipes_create'),
    path('recipes/<int:pk>/update/', views.RecipeUpdate.as_view(), name='recipes_update'),
    path('recipes/<int:pk>/delete/', views.RecipeDelete.as_view(), name='recipes_delete'),
    path('meals/<int:meal_id>/assoc_recipe/<int:recipe_id>/', views.assoc_recipe, name='assoc_recipe'),
    path('recipes/<int:recipe_id>/add_photo/', views.add_photo, name='add_photo'),
    path('accounts/signup/', views.signup, name='signup'),
]

mealplanner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')), 
]

main_app/models.py
from django.db import models
from datetime import date
from django.urls import reverse 
from django.contrib.auth.models import User

# Create your models here.
MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)
class Recipe(models.Model):
    name = models.CharField(max_length=100)  
    url =  models.CharField(max_length=250) 
    photo_url = models.CharField(max_length=250)
    blog_name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('recipe_detail', kwargs={'pk': self.id})    
        
    class Meta:
        ordering = ['-id']     

class Plan(models.Model):
    name = models.CharField(max_length=100)
    start = models.DateField()
    end = models.DateField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("detail", kwargs={"plan_id": self.id})
        
class Meal(models.Model):
    date = models.DateField('meal date')
    name = models.CharField(max_length=100)
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
    ) 
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE) 
    recipe = models.ManyToManyField(Recipe)     

    def __str__(self):
        return f"{self.name}, {self.get_meal_display()} on {self.date}"

    class Meta:
        ordering = ['date']    

    def get_absolute_url(self):
        return reverse("detail", kwargs={"plan_id": self.id})    

class Photo(models.Model):
    url = models.CharField(max_length=200)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)        

    def __str__(self):
        return f"Photo for recipe_id: {self.recipe_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Meal

class MealForm(ModelForm):
  class Meta:
    model = Meal
    fields = ['date', 'meal', 'name']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .forms import MealForm
from .models import Plan, Meal, Recipe, Photo
import uuid
import boto3
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'djangomealplanner'

# Create your views here.
def home(request):
  return render(request, 'home.html')

@login_required
def plans_index(request):
  plans = Plan.objects.filter(user=request.user)
  return render(request, 'plans/index.html', { 'plans': plans })

@login_required
def plans_detail(request, plan_id):
  plan = Plan.objects.get(id=plan_id)
  recipes = Recipe.objects.all()
  meal_form = MealForm()
  return render(request, 'plans/detail.html', { 'plan': plan, 'recipes': recipes, 'meal_form': meal_form })

@login_required
def add_meal(request, plan_id):
  form = MealForm(request.POST)
  if form.is_valid():
    new_meal = form.save(commit=False)
    new_meal.plan_id = plan_id
    new_meal.save()
  return redirect('detail', plan_id=plan_id)

@login_required
def assoc_recipe(request, meal_id, recipe_id):
  Meal.objects.get(id=meal_id).recipe.add(recipe_id)
  return redirect('/')  

@login_required
def add_photo(request, recipe_id):
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
      s3 = boto3.client('s3')
      key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
      try:
          s3.upload_fileobj(photo_file, BUCKET, key)
          url = f"{S3_BASE_URL}{BUCKET}/{key}"
          photo = Photo(url=url, recipe_id=recipe_id)
          photo.save()
      except:
          print('An error occurred uploading file to S3')
  return redirect('recipes_detail', recipe_id=recipe_id)

@login_required
def recipes_detail(request, recipe_id):
  recipe = Recipe.objects.get(id=recipe_id)
  return render(request, 'main_app/recipe_detail.html', {
    'recipe': recipe
  })  

class PlanCreate(LoginRequiredMixin, CreateView):
  model = Plan
  fields = '__all__'

  def form_valid(self, form):
    form.instance.user = self.request.user  
    return super().form_valid(form)

class PlanUpdate(LoginRequiredMixin, UpdateView):
  model = Plan
  fields = '__all__'
  success_url = '/plans/'  

class PlanDelete(LoginRequiredMixin, DeleteView):
  model = Plan
  success_url = '/plans/'    

class MealDelete(LoginRequiredMixin, DeleteView):
  model = Meal
  success_url = '/plans/'  

class RecipeList(LoginRequiredMixin, ListView):
  model = Recipe

class RecipeCreate(LoginRequiredMixin, CreateView):
  model = Recipe
  fields = '__all__'
  success_url = '/recipes/' 

  def form_valid(self, form):
    form.instance.user = self.request.user  
    return super().form_valid(form)

class RecipeUpdate(LoginRequiredMixin, UpdateView):
  model = Recipe
  fields = '__all__'
  success_url = '/recipes/' 

class RecipeDelete(LoginRequiredMixin, DeleteView):
  model = Recipe
  success_url = '/recipes/'  

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/base.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Meal Planner</title>
   
   
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
      crossorigin="anonymous"
    />
  
     <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    /> 
   
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-sm">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">Django MealPlanner</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
           {% if user.is_authenticated %}
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'recipes_create' %}">Add Recipe</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'recipes_index' %}">View Recipes</a>
              </li>
               <li class="nav-item">
                <a class="nav-link" href="{% url 'plans_create' %}">Add Plan</a>
              </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">View Plans</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
              </li>
              {% else %}
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
             <li class="nav-item">
                <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Log In</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}
  
    </main>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
      crossorigin="anonymous"
    ></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %} 
{% block content %}

<h1>Welcome to Django Meal Planner!</h1>

<h3>Add some recipies or add a Meal Plan and start planning!</h1>

{% endblock %}

main_app/templates/main_app/meal_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Meal</h1>

  <h4>Are you sure you want to delete <span class="red-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn btn-danger">
    <a href="{% url 'detail' object.id %}" class="btn btn-warning">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/plan_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Plan</h1>

  <h4>Are you sure you want to delete <span class="red-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn btn-danger">
    <a href="{% url 'detail' plan.id %}" class="btn btn-warning">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/plan_form.html
{% extends 'base.html' %}
{% block content %}
   {% if object %}
        <h1>Edit {{object.name}}</h1>
    {% else %}
        <h1>Add new Plan</h1>
    {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post" class="form-control w-50 shadow-lg">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <div class="card-body">
      
      {{ form.as_p }}
    </div>
    <input type="submit" value="Submit" class="btn btn-success">
  </form>
{% endblock %}

main_app/templates/main_app/recipe_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Recipe</h1>

  <h4>Are you sure you want to delete {{ object.name }}?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn btn-danger">
    <a href="{% url 'recipes_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/recipe_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Recipe Details</h1>

<div class="card rounded-3 shadow-lg mb-3" style="width: 18rem;">
  <img src="{{ recipe.photo_url }}" class="card-img-top" alt="recipe photo">
  <div class="card-body">
    <h5 class="card-title">{{ recipe.name }}</h5>
    <p class="card-text"> Full recipe from <a href="{{ recipe.url }}" >{{ recipe.blog_name }} </a> </p>
    

    <a href="{% url 'recipes_update' recipe.id %}" class="btn btn-secondary">Edit</a>
    <a href="{% url 'recipes_delete' recipe.id %}" class="btn btn-danger">Delete</a>

     
  </div>
</div>

   {% for photo in recipe.photo_set.all %}
    
      <div class="card rounded-3 shadow-lg mb-3" style="width: 18rem;">
        <img src="{{photo.url}}" class="card-img-top" alt="recipe photo">
      
</div>
    {% empty %}
      <div class="card" style="width: 18rem;">No Photos Uploaded</div>
    {% endfor %}

    <form action="{% url 'add_photo' recipe.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
    {% csrf_token %}
    <input type="file" name="photo-file" >
    <br><br>
    <input type="submit" class="btn btn-secondary" value="Upload Photo">
</form>

{% endblock %}

main_app/templates/main_app/recipe_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit {{object.name}}</h1>
  {% else %}
    <h1>Add Recipe</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post" class="form-control w-50 shadow-lg">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_p }}
    </table>
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

main_app/templates/main_app/recipe_list.html
{% extends 'base.html' %} {% block content %}

<h1>Recipe List</h1>

{% for recipe in recipe_list %}

<div id="recipes" class="card rounded-3 shadow-lg mb-3" style="width: 18rem">
  <img src="{{ recipe.photo_url }}" class="card-img-top" alt="recipe photo" />
  <div class="card-body">
    <h5 class="card-title">{{ recipe.name }}</h5>
    <p class="card-text">
      Full recipe from <a href="{{ recipe.url }}"> {{ recipe.blog_name }} </a><br />
      <a href="{% url 'recipes_detail' recipe.id %}" class="btn btn-primary">Details</a>
    </p>
  </div>
</div>

{% endfor %} {% endblock %}

main_app/templates/plans/detail.html
{% extends 'base.html' %} 
{% block content %}

<h1>Plan Details</h1>

<div class="card rounded-3 shadow-lg mb-3" style="width: 18rem">
  <div class="card-body">
    <h5 class="card-title pb-2">{{ plan.name }}</h5>

    <p>Start: {{ plan.start }}</p>
    <p>End: {{ plan.end }}</p>
    <a href="{% url 'plans_update' plan.id %}" class="btn btn-primary">Edit </a>
    <a href="{% url 'plans_delete' plan.id %}" class="btn btn-danger">Delete</a>
  </div>
</div>
</div> 
<div class="card rounded-3 shadow-lg mb-1" style="width: 18rem">
  <form  action="{% url 'add_meal' plan.id %}" method="post">
    {% csrf_token %}
    {{ meal_form.as_p }}
    <input type="submit" class="btn btn-primary" value="Add Meal">
  </form>
  </div>
{% comment %} begin meal list {% endcomment %}
 <div class="card rounded-3 shadow-lg w-75" >
  <div class="card-body">
    {% for meal in plan.meal_set.all %}
      {{meal.date}} - {{meal.get_meal_display}} - {{meal.name}} 
      {% comment %} basic display above {% endcomment %}
    {% if meal.recipe.count %}
      {% for recipe in meal.recipe.all %}
        <a href="{% url 'recipes_detail' recipe.id  %}">Recipe </a>
      {% endfor %}
      {% comment %} if it has a recipe attached, show the recipe as a link {% endcomment %}
      {% else %}
      
   <form action="#" method="post">
    {% csrf_token %}
      <select class="form-select form-select-sm w-auto" aria-label=".form-select-sm example">
        <option selected>Add a Recipe</option>
        {% for recipe in recipes %}
        <option value="{{ recipe.id }}">{{ recipe.name }}</option>
        {% endfor %}
      </select>
      
      <button class="btn btn-secondary btn-sm " type="submit" >
        Add
      </button> 
    </form>
    <br />
   
     {% endif %}

    <a href="{% url 'meal_delete' meal.id %}" class="btn btn-sm btn-danger mb-4"> delete meal </a>  <br />  
    
     {% endfor %}
    {% comment %} end meal list.  {% endcomment %}
  </div>
</div>


{% endblock %}

main_app/templates/plans/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Plan List</h1>

{% for plan in plans %}
  <div class="card mb-2 shadow-lg w-75">
    <a id="plans" href="{% url 'detail' plan.id %}">
    <div class="card-body">
    <h5 class="card-title">{{ plan.name }}</h5>
      
      <p>{{ plan.start }} - {{ plan.end }}</p>
         </div>
  </a>
  </div>
{% endfor %}

{% endblock %}